import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import ContextProvider from "@/context/ContextProvider"
import GoogleAuthProvider from "@/components/providers/GoogleAuthProvider"
import AuthContext from "@/context/AuthContext"
import Sidebar from "@/components/shared/Sidebar"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-primary-500 flex min-h-screen`}>
        <AuthContext>
          <ContextProvider>
            <GoogleAuthProvider>
              <Sidebar />
              {children}
            </GoogleAuthProvider>
          </ContextProvider>
        </AuthContext>
      </body>
    </html>
  )
}
